version: "3.7"
services:
  api:
    image: fire-callback-srv:0.01
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 2048M
    ports:
      - "18015:18015"
    networks:
      - net
    volumes:
      - /data/server/fire-callback-srv/:/app/
networks:
  net:
