version: "3.7"
services:
  api:
    image: srv:0.01
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 2048M
    ports:
      - "8015:8015"
    networks:
      - net
    volumes:
      - /data/srv/:/app/
networks:
  net:
